export default {
  common: { copy: '复制', copied: '已复制!', download: '下载', share: '分享', startNow: '立即开始', learnMore: '了解更多' },
  nav: { home: '首页', platform: '平台', guide: '指南', scripts: '话术', materials: '素材', faq: '问答' },
  invite: { title: '输入您的邀请码', placeholder: '邀请码', yourLink: '您的邀请链接:', linkReady: '链接已生成!', copyLink: '复制链接', shareToTelegram: '分享到Telegram', createLink: '创建您的邀请链接', hint: '💡 在TezBarakat应用 → 邀请 中找到您的邀请码' },
  home: { welcome: { title: '欢迎！👋', subtitle: 'TezBarakat - 团购平台。邀请朋友并赚钱！' }, inviteEarn: { title: '邀请 = 赚钱！💰', subtitle: '创建您的链接并发送给朋友' }, subsidy: { badge: '特别补贴！', title: '1000万索莫尼补贴！', subtitle: '为什么商品这么便宜？因为我们提供补贴！' }, title: 'TezBarakat推广者工具包', subtitle: '一站式推广资源中心', step1: '第1步：创建链接', step1Hint: '从应用中复制您的邀请码：', step2: '推广需要什么？', createLink: '创建链接', whatYouNeed: '推广需要什么?', scripts: { title: '准备好的文本', desc: '说什么? 现成话术!' }, materials: { title: '图片和海报', desc: '下载并分享' }, guide: { title: '如何开始?', desc: '分步指南' }, platform: { title: 'TezBarakat是什么?', desc: '了解平台详情' }, stats: { safe: '100%\n安全', income: '~450\n索莫尼/月', promoters: '3000+\n推广者' } },
  platform: { title: '便宜商品 + 额外收入', subtitle: '三人拼团，一人得货，其他人得积分。', subsidy: { badge: '特别补贴!', title: '1000万索莫尼补贴!', why: '为什么这么便宜?', answer: '👉 因为我们补贴!' }, howItWorks: { title: '如何运作?', step1: { title: '1. 支付', desc: '支付1/3价格' }, step2: { title: '2. 等待', desc: '系统选择中奖者' }, step3: { title: '3. 获得结果', desc: '商品或100%积分!' }, guarantee: '❌ 没中奖? → 100%积分返还!' }, features: { referral: { title: '邀请=赚钱! 💰' }, points: { title: '1积分=1索莫尼 💎' }, safety: { title: '资金安全! 🔒' }, wheel: { title: '幸运转盘 🎡' }, trust: { title: '为什么可以信任?' } } },
  guide: { title: '5分钟=开始赚钱! ⏱️', subtitle: '5分钟学会TezBarakat!', steps: [{ title: '注册', desc: '打开@tezbarakatbot', bonus: '🎁 10免费积分!' }, { title: '充值', desc: 'DC Bank/Alif', min: '最低: 10索莫尼' }, { title: '参与拼团', desc: '支付1/3价格' }, { title: '使用积分', desc: '积分商城', rate: '1积分=1索莫尼' }, { title: '邀请赚钱', desc: '5%-3%-1%', income: '🎉 被动收入!' }], calculator: { title: '收入计算器', result: '月收入' } },
  scripts: { title: '说什么?', subtitle: '准备好的话术', bestScripts: '最佳话术', categories: { family: '家人', friends: '朋友', students: '学生', colleagues: '同事', telegram: 'Telegram', subsidy: '补贴' }, items: { family: ['妈妈，我发现一个新应用！三人拼团，一人得货。没中奖钱会变成积分返还。零风险！👉'], friends: ['朋友，听说过TezBarakat吗？商品便宜，没中奖也能拿回钱！👉'], students: ['同学，有个学生专属应用！商品便宜，钱会返还。👉'], colleagues: ['同事，知道TezBarakat吗？100%保障的拼团。👉'], telegram: ['🛒 TezBarakat - 有保障的拼团!\n✅ 3倍便宜\n✅ 100%返还\n👉'], subsidy: ['知道为什么TezBarakat这么便宜吗？平台补贴1000万！👉'] }, objections: { title: '异议回复', items: [{ q: '这是赌博吗?', a: '不是！100%返还积分。' }, { q: '为什么这么便宜?', a: '平台补贴!' }, { q: '可以信任吗?', a: '是的！与DC Bank和Alif合作。' }] }, tips: { title: '💡 提示', items: ['输入您的邀请码'] } },
  materials: { title: '素材库', subtitle: '准备好的素材', downloadAll: '下载全部', items: [{ id: 1, title: '拼团介绍', file: '01-GroupBuy-Infographic-TJ.png' }, { id: 2, title: '邀请系统', file: '02-Referral-Infographic-TJ.png' }, { id: 3, title: '积分商城', file: '03-PointsMall-Infographic-TJ.png' }, { id: 4, title: '快速入门', file: '04-QuickStart-Infographic-TJ.png' }, { id: 5, title: '资金安全', file: '05-FundSafety-Infographic-TJ.png' }, { id: 6, title: '幸运转盘', file: '06-SpinWheel-Poster-TJ.png' }] },
  faq: { title: '常见问题', subtitle: '常见问题解答', search: '搜索...', items: [{ q: '这是赌博吗?', a: '不是！100%返还。' }, { q: '为什么便宜?', a: '1000万补贴!' }, { q: '可以信任吗?', a: '是的！DC Bank, Alif。' }, { q: '如何开始?', a: '@tezbarakatbot' }, { q: '如何赚钱?', a: '5%-3%-1%' }], contact: { telegram: '@tezbarakat', phone: '+992 770000611', address: '杜尚别' } },
};
